
// COUNTER ACTIONS
export const INC_COUNTER = 'INC_COUNTER'
export const ADD_COUNTER = 'ADD_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const SUBSTRACT_COUNTER = 'SUBSTRACT_COUNTER'
export const STORE_RESULT = 'STORE_RESULT'
export const DELETE_RESULT = 'DELETE_RESULT'
export const RESET_STORE = 'RESET_STORE'

// AUTH ACTIONS
export const CHANGE_USER_LOGIN = 'CHANGE_USER_LOGIN'
export const CHANGE_USER_LOGOUT = 'CHANGE_USER_LOGOUT'

// SAGAS
export const STORE_RESULT_INIT = 'STORE_RESULT_INIT'
export const DELETE_RESULT_INIT = 'DELETE_RESULT_INIT'
